name: "Build Profile README Template Substitutions"
description: "Builds a JSON object for substitutions in a README template file from a repo"

inputs:
  repositories:
    required: true
    description: "The markdown for the repositories, base64-encoded."
  webring:
    required: true
    description: "The markdown for the webring, base64-encoded."

outputs:
  substitutions:
    description: "JSON object of key-value replacements"
    value: ${{ steps.encode-substitutions.outputs.result }}

runs:
  using: composite
  steps:
    - name: Encode substitutions
      id: encode-substitutions
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          return JSON.stringify({
            repositories: `${{ inputs.repositories }}`,
            webring: `${{ inputs.webring }}`,
          });
