name: "Format Webring Markdown"
description: "Fetches a YAML file defining a webring and formats it into a Markdown string"
inputs:
  owner:
    required: true
  repo:
    required: true
  path:
    required: false
    default: "profile/webring.yaml"

outputs:
  markdown:
    description: "Formatted Markdown string for the webring"

runs:
  using: "node20"
  main: "dist/index.js"
