name: Setup Terraform
description: Set up Terraform (and related tools).

inputs:
  terraform-version:
    description: "The Terraform version to use."
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 #v3.1.1
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false
