name: "Update Profile README"
description: "Updates the profile/README.md file in a repository"

inputs:
  owner:
    required: true
    description: "Owner of the repository"
  github-token:
    required: true
    description: "GitHub token for authentication"

outputs:
  updated:
    description: "true if the file was updated, otherwise false"
    value: ${{ steps.write-profile-readme.outputs.updated }}

runs:
  using: composite
  steps:
    - name: Get Org Repos Info
      id: get-org-repos-info
      uses: bitterbridge/github-actions/get-org-repos-info@main
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        owner: ${{ inputs.owner }}

    - name: Format Org Repos Info
      id: format-org-repos-info-md
      uses: bitterbridge/github-actions/format-org-repos-info-md@main
      with:
        repos: ${{ steps.get-org-repos-info.outputs.repos }}

    - name: Format Webring Markdown
      id: format-webring-md
      uses: bitterbridge/github-actions/format-webring-md@main
      with:
        owner: 'bitterbridge' # This is static, as the webring is hosted in the bitterbridge org
        repo: '.github'

    - name: Build Profile README Template Substitutions
      id: build-profile-readme-template-substitutions
      uses: bitterbridge/github-actions/build-profile-template-substitutions@main
      with:
        repositories: ${{ steps.format-org-repos-info-md.outputs.base64 }}
        webring: ${{ steps.format-webring-md.outputs.base64 }}

    - name: Render Profile Template
      id: render-profile-template
      uses: bitterbridge/github-actions/render-profile-template@main
      with:
        owner: ${{ inputs.owner }}
        repo: '.github'
        path: 'profile/README.md.template'
        substitutions: ${{ steps.build-profile-readme-template-substitutions.outputs.substitutions }}

    - name: Write Profile README
      id: write-profile-readme
      uses: bitterbridge/github-actions/write-profile-readme@main
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        owner: ${{ inputs.owner }}
        repo: '.github'
        content: ${{ steps.render-profile-template.outputs.markdown }}
