name: "Update Profile README"
description: "Updates the profile/README.md file in a repository"

inputs:
  owner:
    required: true
    description: "Owner of the repository"
  github-token:
    required: true
    description: "GitHub token for authentication"

outputs:
  updated:
    description: "true if the file was updated, otherwise false"
    value: ${{ steps.write-profile-readme.outputs.updated }}

runs:
  using: composite
  steps:
      - name: Get Org Repos Info
        id: get-org-repos-info
        uses: ./get-org-repos-info
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
        with:
          owner: ${{ inputs.owner }}

      - name: Format Org Repos Info
        id: format-org-repos-info-md
        uses: ./format-org-repos-info-md
        with:
          repos: ${{ steps.get-org-repos-info.outputs.repos }}

      - name: Format Webring Markdown
        id: format-webring-md
        uses: ./format-webring-md
        with:
          owner: ${{ inputs.owner }}
          repo: '.github'

      - name: Build Profile README Template Substitutions
        id: build-profile-readme-template-substitutions
        uses: ./build-profile-template-substitutions
        with:
          repositories: ${{ steps.format-org-repos-info-md.outputs.markdown }}
          webring: ${{ steps.format-webring-md.outputs.markdown }}

      - name: Render Profile Template
        id: render-profile-template
        uses: ./render-profile-template
        with:
          owner: ${{ inputs.owner }}
          repo: '.github'
          path: 'profile/README.md.template'
          substitutions: ${{ steps.build-profile-readme-template-substitutions.outputs.substitutions }}

      - name: Write Profile README
        id: write-profile-readme
        uses: ./write-profile-readme
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
        with:
          owner: ${{ inputs.owner }}
          repo: '.github'
          content: ${{ steps.render-profile-template.outputs.markdown }}
