name: Terraform Test
description: Run `terraform test` to execute automated tests for Terraform configurations.

inputs:
  current-working-directory:
    description: "The path to the Terraform working directory."
    required: true

runs:
  using: composite
  steps:
    - name: Terraform Test
      shell: bash
      current-working-directory: ${{ inputs.current-working-directory }}
      run: |
        terraform test \
          -no-color;
