name: Get Repo Emoji
description: Get the emoji for a given repository.

inputs:
  owner:
    description: "The owner of the repository."
    required: true
  repo:
    description: "The name of the repository."
    required: true
  github-token:
    required: true
    description: "GitHub token for accessing the repository"

outputs:
  emoji:
    description: "The emoji for the repository."
    value: ${{ steps.get-emoji.outputs.emoji }}

runs:
  using: "node20"
  main: "dist/index.js"