name: Dependabot Auto-Merge
on: pull_request

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'bitterbridge/github-actions'

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Assume IAM Role
        id: assume-iam-role
        uses: ./assume-iam-role
        with:
          role-to-assume: ${{ vars.IAM_ROLE_TO_ASSUME }}

      - name: Get GitHub Token
        id: get-github-token
        uses: ./get-github-token

      - name: Dependabot Auto-Merge
        id: dependabot-auto-merge
        uses: ./dependabot-auto-merge
        with:
          github-token: ${{ steps.get-github-token.outputs.github-token}}
          package-ecosystems: '["github_actions"]'
          pull-request-id: ${{ github.event.pull_request.number }}
