name: Test write-profile-readme
run-name: Test the `write-profile-readme` action

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Assume IAM Role with defaults
        id: assume-iam-role
        uses: ./assume-iam-role
        with:
          role-to-assume: ${{ vars.IAM_ROLE_TO_ASSUME }}

      - name: Get GitHub Token
        id: get-github-token
        uses: ./get-github-token
        with:
          github-app-id-secret-path: ${{ vars.APP_ID_SECRET_PATH }}
          github-app-private-key-secret-path: ${{ vars.APP_PRIVATE_KEY_SECRET_PATH }}

      - name: Get Org Repos Info
        id: get-org-repos-info
        uses: ./get-org-repos-info
        env:
          GITHUB_TOKEN: ${{ steps.get-github-token.outputs.github-token }}
        with:
          owner: 'bitterbridge'

      - name: Format Org Repos Info
        id: format-org-repos-info-md
        uses: ./format-org-repos-info-md
        with:
          repos: ${{ steps.get-org-repos-info.outputs.repos }}

      - name: Build Profile README Template Substitutions
        id: build-profile-readme-template-substitutions
        uses: ./build-profile-template-substitutions
        with:
          repositories: ${{ steps.format-org-repos-info-md.outputs.markdown }}

      - name: Render Profile Template
        id: render-profile-template
        uses: ./render-profile-template
        with:
          owner: 'bitterbridge'
          repo: '.github'
          path: 'profile/README.md.template'
          substitutions: ${{ steps.build-profile-readme-template-substitutions.outputs.substitutions }}

      - name: Write Profile README
        id: write-profile-readme
        uses: ./write-profile-readme
        env:
          GITHUB_TOKEN: ${{ steps.get-github-token.outputs.github-token }}
        with:
          owner: 'bitterbridge'
          repo: '.github'
          content: ${{ steps.render-profile-template.outputs.markdown }}
