name: Test get-repo-emoji
run-name: Test the `get-repo-emoji` action

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Assume IAM Role with defaults
        id: assume-iam-role
        uses: ./assume-iam-role
        with:
          role-to-assume: ${{ vars.IAM_ROLE_TO_ASSUME }}

      - name: Get GitHub Token
        id: get-github-token
        uses: ./get-github-token
        with:
          github-app-id-secret-path: ${{ vars.APP_ID_SECRET_PATH }}
          github-app-private-key-secret-path: ${{ vars.APP_PRIVATE_KEY_SECRET_PATH }}

      - name: Get Repo Info
        id: get-info
        uses: ./get-repo-info
        env:
          GITHUB_TOKEN: ${{ steps.get-github-token.outputs.github-token }}
        with:
          repo: 'github-actions'
          owner: 'bitterbridge'

      - name: Show Repo Info
        id: show-info
        shell: bash
        run: |
          echo "The info for the repository is: ${{ steps.get-info.outputs.info }}"
